PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE idioms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    russian TEXT NOT NULL,
    french TEXT NOT NULL
);
INSERT INTO idioms VALUES(1,'Белая ворона','Un mouton à cinq pattes');
INSERT INTO idioms VALUES(2,'Биться как рыба об лед','Tirer le diable par la queue');
INSERT INTO idioms VALUES(3,'Бросать тень на кого-либо (что-либо)','Entacher la réputation');
INSERT INTO idioms VALUES(4,'Быть между молотом и наковальней','Etre entre l’enclume et le marteau');
INSERT INTO idioms VALUES(5,'Быть на седьмом небе','Etre aux anges');
INSERT INTO idioms VALUES(6,'Быть не на своём месте','Ne pas être à sa place');
INSERT INTO idioms VALUES(7,'Быть у кого-либо под башмаком','C’est elle qui porte la culotte');
INSERT INTO idioms VALUES(8,'Вертеться как белка в колесе','Faire feu des quatre fers');
INSERT INTO idioms VALUES(9,'Взять себя в руки','Se domineer');
INSERT INTO idioms VALUES(10,'Вилами на воде писано','Ce n’est pas dans la poche');
INSERT INTO idioms VALUES(11,'Висеть на волоске','Ne tenir qu’à un fil');
INSERT INTO idioms VALUES(12,'Висеть на телефоне','Etre pendu au telephone');
INSERT INTO idioms VALUES(13,'Водить кого-либо за нос','Mener qn an bateau');
INSERT INTO idioms VALUES(14,'Водой не разольешь','Ils sont (comme) les deux doigts de la main');
INSERT INTO idioms VALUES(15,'Вот где собака зарыта','C’est là que gît le lièvre');
INSERT INTO idioms VALUES(16,'Вставать с левой ноги','Se lever du pied gauche');
INSERT INTO idioms VALUES(17,'Выйти из себя','Sortir de ses gonds');
INSERT INTO idioms VALUES(18,'Голодный как волк','Il a une faim de loup');
INSERT INTO idioms VALUES(19,'Делать из мухи слона','Faire d’une mouche un elephant');
INSERT INTO idioms VALUES(20,'Денег куры не клюют','Etre cousu d’or');
INSERT INTO idioms VALUES(21,'Душа нараспашку','Il a le cœur sur la main');
INSERT INTO idioms VALUES(22,'Душа ушла в пятки','Il a une peur bleue');
INSERT INTO idioms VALUES(23,'Жить как на вулкане','Danser sur un volcan');
INSERT INTO idioms VALUES(24,'Замести следы','Brouiller les pistes');
INSERT INTO idioms VALUES(25,'Зарубить на носу','Se mettre ach dans la tête');
INSERT INTO idioms VALUES(26,'Звёзд с неба не хватает','Il n’a pas inventé la poudre');
INSERT INTO idioms VALUES(27,'Играть с огнем','Jouer avec le feu');
INSERT INTO idioms VALUES(28,'Излить душу','Ouvrir son cœr');
INSERT INTO idioms VALUES(29,'Искать иголку в стоге сена','Chercher une aiguille dans une botte de foin');
INSERT INTO idioms VALUES(30,'Испить чашу до дна','Boire le calice jusqu’à la lie');
INSERT INTO idioms VALUES(31,'Как ветром сдуло','Disparu comme par enchantement');
INSERT INTO idioms VALUES(32,'Как гром среди ясного неба','Comme un coup de foudre dans un ciel serein');
INSERT INTO idioms VALUES(33,'Как дважды два четыре','Claire comme le jour');
INSERT INTO idioms VALUES(34,'Как об стенку горох','Autant parler à un sourd');
INSERT INTO idioms VALUES(35,'Как сельдей в бочке','Serrés comme des harengs en boîte');
INSERT INTO idioms VALUES(36,'Камень на сердце','Avoir le cœur lourd');
INSERT INTO idioms VALUES(37,'Капля в море','Une goutte d’eau dans la mer');
INSERT INTO idioms VALUES(38,'Кататься как сыр в масле','Vivre comme un coq en pâte');
INSERT INTO idioms VALUES(39,'Клин клином выбивать','Un clou chasse l’autre');
INSERT INTO idioms VALUES(40,'Красивый жест','Un beau geste');
INSERT INTO idioms VALUES(41,'Крепкий орешек','Un dur à cuire');
INSERT INTO idioms VALUES(42,'Купить кота в мешке','Acheter chat en poche');
INSERT INTO idioms VALUES(43,'Лить как из ведра','Il pleut à seaux');
INSERT INTO idioms VALUES(44,'Ловить рыбу в мутной воде','Pêcher en eau trouble');
INSERT INTO idioms VALUES(45,'Мерить на свой аршин','Mesurer les autres à son aune');
INSERT INTO idioms VALUES(46,'Мир тесен','Le mond est petit');
INSERT INTO idioms VALUES(47,'Нажать на все кнопки','Faire jouer tous les ressorts');
INSERT INTO idioms VALUES(48,'Называть вещи своими именами','Appeler un chat un chat');
INSERT INTO idioms VALUES(49,'Нем как рыба','Muet comme une carpe');
INSERT INTO idioms VALUES(50,'Обещать золотые горы','Prommetre monts et merveilles');
INSERT INTO idioms VALUES(51,'Переливать из пустого в порожнее','Donner un coup d’épée dans l’eau');
INSERT INTO idioms VALUES(52,'Плавать как топор','Nager comme un fer à repasser');
INSERT INTO idioms VALUES(53,'Плевать в потолок','Ne rien faire de ses dix doigts');
INSERT INTO idioms VALUES(54,'Поджать хвост','Avoir l’oreille basse');
INSERT INTO idioms VALUES(55,'Похожи как две капли воды','Se ressembler comme dux gouttes d’au');
INSERT INTO idioms VALUES(56,'Пройти сквозь огонь и воду','En voir de toutes les couleurs');
INSERT INTO idioms VALUES(57,'Стреляный воробей','Il en a vu d’autres');
INSERT INTO idioms VALUES(58,'Убить двух зайцев','Faire d’une Pierre deux coups');
INSERT INTO idioms VALUES(59,'Ходить вокруг да около','Tourner autour du pot');
INSERT INTO idioms VALUES(60,'Худой как спичка','Maigre comme un clou');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('idioms',60);
COMMIT;
